engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - src/**/*.php
  - src/**/*.js
  - src/**/*.css
  - tests/**/*.php
exclude_paths:
- src/font-awesome/**/*
