language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - php: 5.3
  - php: 5.4
  - php: 5.5
  - php: 5.6
  - php: 7.0
  - php: hhvm

env:
  - env: WP_VERSION=3.7 WP_MULTISITE=0
  - env: WP_VERSION=3.8 WP_MULTISITE=0
  - env: WP_VERSION=3.9 WP_MULTISITE=0
  - env: WP_VERSION=4.0 WP_MULTISITE=0
  - env: WP_VERSION=4.1 WP_MULTISITE=0
  - env: WP_VERSION=4.2 WP_MULTISITE=0
  - env: WP_VERSION=4.3 WP_MULTISITE=0
  - env: WP_VERSION=4.4 WP_MULTISITE=0
  - env: WP_VERSION=latest WP_MULTISITE=0

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install --dev

script: phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN=c0e18ea554a37a7495947a34c818939c0599bde7c1efa3ee136989c053dde9da ./vendor/bin/test-reporter

addons:
    code_climate:
        repo_token: c0e18ea554a37a7495947a34c818939c0599bde7c1efa3ee136989c053dde9da