language: php

notifications:
  email:
    on_success: never
    on_failure: always

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

env:
  - WP_VERSION=4.6.12 WP_MULTISITE=0
  - WP_VERSION=4.7.11 WP_MULTISITE=0
  - WP_VERSION=4.8.7 WP_MULTISITE=0
  - WP_VERSION=4.9.8 WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=0

stages:
  - validate
  - test

jobs:
  include:
  - stage: validate
    name: "Basic Checks"
    php: 7.2
    before_install:
      - composer require bartlett/php-compatinfo:5.* --dev
      - composer require phpunit/phpunit:5.7 --dev
    before_script: skip
    script: ./vendor/bin/phpunit -c phpunit-checks.xml --no-coverage
  - stage: test
    name: 'Latest versions'
    env: WP_VERSION=4.9.8 WP_MULTISITE=0
    php: '7.2'
    before_install:
      - composer require codeclimate/php-test-reporter:dev-master --dev
      - composer require phpunit/phpunit:5.7 --dev
    script: ./vendor/bin/phpunit
    after_script:
      - CODECLIMATE_REPO_TOKEN=c0e18ea554a37a7495947a34c818939c0599bde7c1efa3ee136989c053dde9da ./vendor/bin/test-reporter

matrix:
  allow_failures:
    - env: WP_VERSION=nightly WP_MULTISITE=0
  fast_finish: true

before_install: composer require phpunit/phpunit:5.7 --dev
install: composer install --prefer-source
before_script: bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: ./vendor/bin/phpunit --no-coverage
