language: php

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    secure: i6jy0Y/EiplpnJVw47cJuB3isSh19qI5F9bj299/jGb+4IBXkZh6k8jjn13Amg3P59ydOowPtI+tyYw9vu84rTQ03giddcyyPK7qxZziyJ+y5/fhsA8gHPgexA0pxA/wt6Hp6QzDC+jmPVSXSZ6ImYTDz6dk+arfQd5oGVHcfgRB+o6enw6J3Q+yt6YugyJoVpETO71aj7u/LE44yVk49SJTnQBaqXGLrWPT1uBaINzheAvPO0oICHCoqUK3XKR3b5UCvILywBkbyc01gyPO0CpT3TPPyfXR8nburkzEG+b2bKbrMD9kWnIXxNiue+zOB0jLKK2yJw7AHOewUek9J93mvzk7204CNeu5uA8xAEO2BiiRky+KhL+HHhnUHe7YlvL1xHZMlw/u0BzAgUsoELnFZb5FawiQ2lw8CuNTxCL91sQqvpMCTYAmJqZpWjZRaj8wSUm/3jiMjgIrhWv5rDnmeQJEPN+v5ZGs91yyXwEMVnsXePNx+13/3HrCFYpCawfb8S+1UljR+kZ4YJuX0+zE86x8pCGl4AOHGafvUY3T014ma0CWTvvW264fvS9NmJirRkTVsilvQACuL2RW3yl7gXqhCaTWRAm4P3F5V2K5+SKqaHVz4+Hd/jSXTr5Q0UKfdW9EuDU9YId+89JkDRq+nRwNMgv4wrrD6T7mo6E=
branches:
  except:
  - /^feature\/[-\w]+$/

php:
  - '5.6'
  - '7.2'

env:
  - WP_VERSION=4.7.13 WP_MULTISITE=0
  - WP_VERSION=4.8.9 WP_MULTISITE=0
  - WP_VERSION=4.9.10 WP_MULTISITE=0
  - WP_VERSION=5.0.5 WP_MULTISITE=0
  - WP_VERSION=5.1.1 WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=0

stages:
  - validate
  - test

jobs:
  include:
  - stage: validate
    name: "Basic Checks"
    php: '7.3'
    before_install:
      - phpenv config-rm xdebug.ini
      - composer require bartlett/php-compatinfo:5.* --dev
      - composer require phpunit/phpunit:5.7.* --dev
    before_script: skip
    script: ./vendor/bin/phpunit -c phpunit-checks.xml --no-coverage
  - stage: validate
    name: 'Minimum requirement'
    env: WP_VERSION=4.7 WP_MULTISITE=0
    php: '5.3'
    dist: precise
    before_install:
      - phpenv config-rm xdebug.ini
      - composer require phpunit/phpunit:4.8.* --dev
    script: ./vendor/bin/phpunit --no-coverage --exclude-group unittests
  - stage: validate
    name: 'Latest versions'
    env: WP_VERSION=5.1.1 WP_MULTISITE=0
    php: '7.3'
    before_install: composer require phpunit/phpunit:5.7.* --dev
    before_script:
      - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
    script: ./vendor/bin/phpunit
    after_script:
      - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT
  - stage: test
    name: 'Latest versions, pretty permalinks'
    env: WP_VERSION=5.1.1 WP_MULTISITE=0 WP_TESTS_PERMALINK=PRETTY
    php: '7.3'
  - stage: test
    name: 'Latest versions, PATHINFO permalinks'
    env: WP_VERSION=5.1.1 WP_MULTISITE=0 WP_TESTS_PERMALINK=PATHINFO
    php: '7.3'

matrix:
  exclude:
    - env: WP_VERSION=nightly WP_MULTISITE=0
      php: '5.6'
  allow_failures:
    - env: WP_VERSION=nightly WP_MULTISITE=0
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer require phpunit/phpunit:5.7.* --dev
install: composer install --prefer-source
before_script: bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: ./vendor/bin/phpunit --no-coverage
